### ISSUE TITLE
USER STORY: #1

### ISSUE THREAD

**Issue by NoraPDev** [NoraPDev/love-running#1]
In order to **meet with fellow runners** as a **user**, I can **chat to them online**

**Acceptance Criteria:**

- Have a designated chat area, where you can put text
- Have emoticons added
- See who is available online

**Tasks:**

- [ ] Create the chat area, with emoticons added
- [ ] Have a submit button
- [ ] Create a list of users
